### ISSUE TITLE
json/hstore and types=list()

### ISSUE THREAD

**Issue by justinpryzby** [PyGreSQL/PyGreSQL#38]
Am 06.05.2020 um 06:01 schrieb Justin Pryzby:                                                                                                                                                        
> I'm using jsonb column for the 2nd time ever, and a variation of my issue from
> August came up again.
>
> 1) I thougt it was weird to need to pass types=['something', 'else', 'int',
> 'float', 'json'].  I suggest to also do:
> if isinstance(types, str):
>    types=types.split()
>
> 2) I suggested to allow passing not types=[str('json')] but also types=[pg.Json].
>
> 3) I suggested guess_simple_types() should handle Json() and Hstore()
>
> 4) I think we need an example of this, probably for types=list() and for
> types=dict().
On Fri, Aug 23, 2019 at 11:01:11AM -0500, Justin Pryzby wrote:
[original message elided]

**Comment by Cito** [comment]
All four suggestions have been implemented in version 5.2.
