### ISSUE TITLE
cursor.copy_from() method doesn't work with quoted named tables

### ISSUE THREAD

**Issue by otaviomguerra** [PyGreSQL/PyGreSQL#47]
The error below is thrown when trying to copy a CSV file into a given Postgres table that have quotes in the name in order to use CamelCase style.

The Error message is:

```
pg.ProgrammingError: ERROR:  syntax error at or near "User"
LINE 1: copy "public."User"" from stdin (format csv,delimiter ','...
```

The code that generates the error:

```python

cursor.copy_from(file, "public.\"User\"", null="") 

```

where file is the csv file object and the second argument is the ```schema.table``` name

Trying others names to the schema.table such as ```'public."User"'``` or any variations doesn't work.

I assume the problem is not a Postgres internal problem because the code above works with **psycopg2**

**Comment by Cito** [comment]
Thanks for reporting. I think the problem is that the table name is always put in quotes internally, no matter whether it cotains dots. This should happen only for unqualified names. Will be fixed.

Just passing "User" should work in your case since "public" is normally on the path.

**Comment by otaviomguerra** [comment]
Thanks for the quick response!

> Just passing "User" should work in your case since "public" is normally on the path.


FYI Passing only the "User" doesn't work either

Gives the following error:

```
pg.ProgrammingError: ERROR:  zero-length delimited identifier at or near """"
LINE 1: copy ""User"" from stdin (format csv,delimiter ',..
```

**Comment by Cito** [comment]
Did you pass it like this? `cursor.copy_from(file, 'User', null='')`

**Comment by otaviomguerra** [comment]
> Did you pass it like this? `cursor.copy_from(file, 'User', null='')`

Sorry for late response. Yes, i tried that. it just throws an error saying that the relation 'User' doesn't exists...

**Comment by Cito** [comment]
Is the table actually called "User" or is it called "user"? If the latter, then you need to pass `'user'`. An additional problem here is that "user" is actually a keyword in SQL. So I think you can't even create a table called "user" unless you quote it. And then the name is case sensitive, so you must care about that.

**Comment by otaviomguerra** [comment]
> Is the table actually called "User" or is it called "user"? If the latter, then you need to pass `'user'`. An additional problem here is that "user" is actually a keyword in SQL. So I think you can't even create a table called "user" unless you quote it. And then the name is case sensitive, so you must care about that.

The table is called "User". Its CamelCased. Changing it to "Usuario" (portuguese) doesn't do any good, so i think the SQL keyword is not a problem here.

**Comment by Cito** [comment]
If it's camelcased, and "public" is in the search path (normally it is), passing just "User" with no additional quotes should work. I have just tested it with Postgres 12 and Pygres 5.1.2. You can check the search path with `show search_path`.

Just to make sure: If you created the table with `CREATE TABLE public."User"` then it's camelcased. If you created it with `CREATE TABLE public.User` then it's actually not camelcased and you must pass "user".

**Comment by otaviomguerra** [comment]
> If it's camelcased, and "public" is in the search path (normally it is), passing just "User" with no additional quotes should work. I have just tested it with Postgres 12 and Pygres 5.1.2. You can check the search path with `show search_path`.

Sorry, I forgot to mention that my PyGreSQL version is **5.0.6**. And indeed **public** is in the search_path. I will double check if it works with the name of the table being parsed as just `User` with no quotes.


> Just to make sure: If you created the table with `CREATE TABLE public."User"` then it's camelcased and you must pass "User". If you created it with `CREATE TABLE public.User` then it's actually not camelcased and you must pass "user".

I created the table with the quotes, so its indeed camelcased as i said. Thanks for the tip anyways!

**Comment by justinpryzby** [comment]
I think the confusion is that the behavior changed in 5.2, which does proper (necessary) quoting/escaping. (However, it fails to handle schemas).  Before 5.2, you would've (could've, but shouldn't have, but maybe needed to) pass '"User"'.  You could've also passed other stuff, like "'; DROP TABLE students; --', so 5.2 fixed that.  But now (in 5.2.0) you cannot pass 'public."User"', since that whole thing is now quoted, and turns into a table in the default namespace called "public.\"User\"".

@cito: I think your current patch is wrong, because it treats "." as special.  But '.' can be a part of the table (or schema) identifier, as long as it's quoted.  I think you'd need to take a schema=None argument, and write something like: table = quote(table) if namespace is None else '{}.{}'.format(quote(schema), quote(table))

Actually, your current patch is probably "usable" (since anyone can write "public." and it only treats the FIRST dot as special).  But I think it's unintuitive and harder to document that "the first is special and here's how to use dotted tablename" than to add a new argument for schema.

**Comment by Cito** [comment]
@justinpryzby - yes, this is more like a "pragmatic workaround". There are also a lot of methods in the `pg` module that take only a table name as a parameter, but no schema name, and they all essentially work like this. In order to be consistent, we would need to add add schema parameters to all of these methods. I'm not sure if this effort is justified just to support people who want to use dots in their table names.

**Comment by justinpryzby** [comment]
On Thu, Aug 06, 2020 at 03:12:23AM -0700, Christoph Zwerschke wrote:
> @justinpryzby - yes, this is more like a "pragmatic workaround". There are also a lot of methods in the `pg` module that take only a table name as a parameter, but no schema name, and they all essentially work like this. In order to be consistent, we would need to add add schema parameters to all of these methods. I'm not sure if this effort is justified just to support people who want to use dots in their table names.

I think you can't properly escape the table name without passing schema
separately, so maybe you should just get rid of the escaping (That means a
behavior change at 5.2 changes back at 5.2.1).

Maybe as a transitional measure, you could accept tablename as a tuple.
If it's a tuple, then you set table = '.'.join(escape(i) for i in table)
Normally should be a tuple of length 2, but 3 or 1 can be ok (db.schema.table).

At telsasoft, we only really use DB.query(), and none of the other helper
functions.  We use schemas, and mixed-case table names in our python code, but
we don't quote them, so postgres sees them as lowercase.

I think with the existing implementation, mixed-case schemas wouldn't work, and
couldn't have chars like "-", and vulnerable to injection (if the table name is
controlled by a user).

-- 
Justin Pryzby
System Administrator
Telsasoft
+1-952-707-8581

**Comment by Cito** [comment]
> Maybe as a transitional measure, you could accept tablename as a tuple.

Sounds like a good solution for the classic API methods like DB.update(table, ...) where we can't change the signature without making it more complicated and backward incompatible. The case where you have "normal", unquoted table names and a single schema is still by far the most frequent one, and we should not make the API more complicated to support the more rare cases.

**Comment by Cito** [comment]
We can consider passing a schema everywhere separately, or allowing (schema, table) tuples in version 5.3. For 5.2, I want to leave things as they are.
