### ISSUE TITLE
Support for sslmode and sslrootcert

### ISSUE THREAD

**Issue by heri16** [PyGreSQL/PyGreSQL#48]
I've been looking around and can't seem to find how to pass these opts: `?sslmode=verify-full&sslrootcert=rds-ca-2019-root.pem`.

Is SSL options supported?

**Comment by Cito** [comment]
For the classic module, use a DSN (or URI), e.g.
```py
db = pg.DB('host=localhost dbname=demo sslmode=verify-full sslrootcert=rds-ca-2019-root.pem')
```
For the DB-API module, use keyword arguments, e.g.
```py
con = pgdb.connect('localhost:demo', sslmode='verify-full', sslrootcert='rds-ca-2019-root.pem')
```
