### ISSUE TITLE
PostgreSQL 13 support

### ISSUE THREAD

**Issue by devrimgunduz** [PyGreSQL/PyGreSQL#49]
Hi,

PostgreSQL 13.0 is due tomorrow. When will you  release v13 compatible version?

Regards, Devrim

**Comment by Cito** [comment]
Thanks for the heads up. Will see if I can get it done this week.

**Comment by Cito** [comment]
PyGreSQL 5.2.1 with support for PostgreSQL 13 and Python 3.9 has been released now.

**Comment by devrimgunduz** [comment]
Thanks a lot! Pushed packages.
