### ISSUE TITLE
PQputline/getline/endcopy are deprecated

### ISSUE THREAD

**Issue by justinpryzby** [PyGreSQL/PyGreSQL#59]
Since postgres v7.4.  The new functions PQputCopyData/PQgetCopyData/PQputCopyEnd have different return values.

Also, sending "\." isn't needed with libpq protocol 3.  pg14 will remove support for libpq protocol 2, so it's about time to remove that.

**Comment by Cito** [comment]
Luckily these functions still work in Pg14, but this should be really changed in the next version of PyGres.

**Comment by Cito** [comment]
This will be released with version 5.2.4 today.
