### ISSUE TITLE
exceptions raised in inserttable loop fail to call endcopy

### ISSUE THREAD

**Issue by justinpryzby** [PyGreSQL/PyGreSQL#60]
> This causes protocol errors:                                                                                                                   
>                                                                                                                                                
> $ python3.5 -c "import pg; d=pg.DB('dbname=postgres host=/tmp'); d.inserttable('loc2', ['b', 'c'])"                                            
> Traceback (most recent call last):                                                                                                             
>    File "<string>", line 1, in <module>                                                                                                        
> TypeError: The second argument must contain a tuple or a list                                                                                  
> ...                                                                                                                                            
> 2021-03-05 14:36:41.297 CST client backend[7161] [unknown] ERROR:  unexpected message type 0x58 during COPY from stdin                         
>                                                                                                                                                
> It looks like this was previously broken by 7f1e84d88, fixed (incidentally) by                                                                 
> b8bd9f763, and most recently broken by b8bd9f763.

**Comment by Cito** [comment]
Should be solved via 3c965127a1a4750393e87f7701fc44de2d14fe14 now.
