### ISSUE TITLE
Support schemas and quoting in DB() and pgdb

### ISSUE THREAD

**Issue by justinpryzby** [PyGreSQL/PyGreSQL#61]
Since commit f82d4cd2, inserttable() escapes the table name, which interferes with use of schemas.
We talked about this in DBAPI2 in issue #47

The table could be passed as a tuple of (namespace, table) or (table,) or (db,namespace,table), which must be individually escaped.  Or take a kwarg which would indicate that the table is already quoted (and might contain schema).

Mixed-case names and special chars should still be supported.

**Comment by Cito** [comment]
Implemented the same pragmatic solution as in the `copy_*` methods of `pgdb` now in 307ec95c40a56d33bf478de72575402f1774981c.

This is only a patch, we should implement a proper solution with the next minor or major version increment.
