### ISSUE TITLE
Error with AWS Lambda

### ISSUE THREAD

**Issue by ReyanshKharga** [PyGreSQL/PyGreSQL#64]
I'm trying this on lambda but getting the following error:

[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': Cannot import shared library for PyGreSQL,
probably because no libpq.so is installed.
No module named '_pg'

**Comment by Cito** [comment]
Probably. But this is not an issue of PyGreSQL. You must install libpq for PyGreSQL to work.
