### ISSUE TITLE
inserttable() fails to escape carriage return

### ISSUE THREAD

**Issue by justinpryzby** [PyGreSQL/PyGreSQL#68]
The escapes for newline, tab, and escape were added in e299a88, which was correct according to documentation for postgres 7.1.
But in 9c48cae3e, this was removed from postgres documentation:

> At present (PostgreSQL 7.2 and older versions) it is possible to represent a data carriage return without any special quoting, and to represent a data newline by a backslash and newline. However, these representations will not be accepted by default in future releases.

https://www.postgresql.org/docs/7.2/sql-copy.html

**Comment by Cito** [comment]
Thanks for the heads up, Justin. Can you review my fix in e27faeca0b28e239fc8f87fed3c96f111032a720?

**Comment by justinpryzby** [comment]
On Sat, Feb 05, 2022 at 06:29:25AM -0800, Christoph Zwerschke wrote:
> Thanks for the heads up, Justin. Can you review my fix in e27faeca0b28e239fc8f87fed3c96f111032a720?

I didn't try it, but it looks right.

Without escaping, it gives this error.

OSError: ERROR:  literal carriage return found in data
HINT:  Use "\r" to represent carriage return.

-- 
Justin

**Comment by Cito** [comment]
Fix will be released with version 5.2.4 today.
