### ISSUE TITLE
inserttable() can miss failure

### ISSUE THREAD

**Issue by justinpryzby** [PyGreSQL/PyGreSQL#72]
```python
import pg
db = pg.DB('postgres')
db.query('CREATE TABLE IF NOT EXISTS t(a smallint)')
db.db.inserttable('t', [[33000]])
#db.query('SELECT 1')
```

Without any following query, the error is never (or not necessarily) sent from the server, and even with a following query, the error is sent but then not raised by pygres.  Patch to follow.

https://www.postgresql.org/docs/current/libpq-copy.html
"After successfully calling [PQputCopyEnd](https://www.postgresql.org/docs/current/libpq-copy.html#LIBPQ-PQPUTCOPYEND), call [PQgetResult](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQGETRESULT) to obtain the final result status of the COPY command"

**Comment by Cito** [comment]
Fixed in #73 with additional test in 8699ace9aee8ff9ccba38695a757f34b2f9149ff.
