### ISSUE TITLE
Occured an error when import Json data with copy_from method

### ISSUE THREAD

**Issue by JinXia77** [PyGreSQL/PyGreSQL#78]
I want to insert the json data into my postgre database by using psycopg2. But an error occured when I insert data by using copy_from function, the error shows below. And the code for writting is shown below. So I want to know how to solve this problem
```python
import psycopg2
from psycopg2.extras import Json
from io import StringIO
import datetime
import fields

id = '12'
words = [{'wd': 'bee', 'wt': 3}, {'wd': 'boat', 'wt': 3}]
keyword_type = 'semantic'
json_words = Json(words)
# send_words = fields.JSONField.to_python(None, json_words)
insert_date = datetime.date(2022,9,6)
company = 'company'
f = ''
for i in range(5):
    f += "{}\t{}\t{}\t{}\t{}\n".format(id, json_words, company, keyword_type, insert_date)

conn = psycopg2.connect(database='postgres', user='postgres', password='***',
                        host='**',
                        port='**')
cur = conn.cursor()
cur.execute('SET search_path TO keywords, public')
cur.copy_from(StringIO(f), "test", columns=('id', 'keywords', 'company', 'mode', 'keyword_date'))
conn.commit()
cur.close()
conn.close()
```
![copy_from_json_error](https://user-images.githubusercontent.com/110447054/188768679-10e15d74-26b3-4904-bdf6-99937e1452dd.png)

**Comment by Cito** [comment]
You're in the wrong issue tracker, this is for PyGreSQL, not psycopg2.

Please ask on the [psycopg2](https://www.psycopg.org/) mailing list how to solve this.

I guess the problem is that you (indirectly) use the `str` method to reder the `Json` object, which creates a quoted string, but the `copy_from` method does not expect quotes.
