### ISSUE TITLE
Classic PyGreSQL API is unaware of generated identity columns

### ISSUE THREAD

**Issue by seneca-c** [PyGreSQL/PyGreSQL#84]
Using SQL standard, generated identity columns with classic PyGreSQL functions like `insert` or `update` columns can result in failures without guard code is written to explicitly remove any references to the generated column from the row dict.  If the identity column was declared as `GENERATED ALWAYS AS IDENTITY`, it cannot be written to unless it is to be reset to its default or explicitly set using `INSERT INTO foo (foo_id, field) OVERRIDING SYSTEM VALUE`.

The value of 'a' in pg_attribute.attidentity indicates these columns that require an explicit override when including them in an `INSERT`.   The value of 'd' indicates a generated identity column that requires no intervention to be overridden, and can always be changed in `UPDATE`.  The special behaviour that 'd' columns have is that the value given to it by an `INSERT` is ignored in favour of the generated sequence if using `INSERT INTO foo (foo_id, field) OVERRIDING USER VALUE`.

**Comment by Cito** [comment]
Same question as in #83: Can you provide a concrete example that fails and that can be used as unit test for fixing this, or maybe even provide a PR?

**Comment by Cito** [comment]
See #83. Fix will be released in version 5.2.5.
