### ISSUE TITLE
Changelog not updated for 6.1.0

### ISSUE THREAD

**Issue by devrimgunduz** [PyGreSQL/PyGreSQL#89]
Hi,

https://pygresql.org/contents/changelog.html still shows 6.0.1 as the latest version.  Can you please update it?

Thanks!

Devrim

**Comment by Cito** [comment]
The pages on [GitHub](https://pygresql.github.io/) and [ReadTheDocs](https://pygresql.readthedocs.io/) are up to date.

The custom website [pygresql.org](https://pygresql.org/) needs to be updated or just resolve to the GitHub page.

I have reported this on the mailing list - @darcyjcain should be able to fix it.

**Comment by devrimgunduz** [comment]
Thanks!. It is done now apparently. Closing.
